#!/usr/bin/env bash
set -euo pipefail

RUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${RUN_DIR}/.." && pwd)"
MODULE_DIR="${RUN_DIR}/algo-modules"
CHECK_OUT="${RUN_DIR}/algo-lib-check.js"
INLINE_OUT="${RUN_DIR}/algo-lib-inline-check.js"
HTML_FILE="${REPO_ROOT}/src/browser/pages/algo-lib.html"
HTML_BACKUP="${HTML_FILE}.bak"
START_MARKER="// ==== ALGO-LIB-JS-START ===="
END_MARKER="// ==== ALGO-LIB-JS-END ===="

SHARED_MODULES=(
  "01-state.js"
  "02-utils.js"
  "03-item-helpers.js"
  "04-nav-router.js"
  "05-data-loading.js"
  "06-cards-list.js"
  "07-categories.js"
  "08-workspace-core.js"
  "09-workspace-import.js"
  "10-workspace-monaco-save.js"
  "11-legacy-create.js"
  "12-editor-shell.js"
  "13-editor-files.js"
  "14-editor-save-namespace.js"
  "15-editor-inline-test-panel.js"
  "16-editor-inline-output-history.js"
  "17-algo-info-admin-publish.js"
  "18-template-test-editor.js"
  "19-template-run-save-publish.js"
  "20-review-submit.js"
  "21-review-admin-actions.js"
  "22-snippets.js"
  "23-settings-review-sse.js"
  "24-terminal-panel.js"
  "25-debug-tools.js"
  "26-run-problems-keys.js"
  "27-auth-myalgos.js"
  "28-users.js"
  "29-full-test-core.js"
  "30-full-test-basic-inputs.js"
  "31-full-test-upload-inputs.js"
  "32-full-test-run-output-compat.js"
  "33-component-test-core.js"
  "34-component-test-widgets.js"
  "35-component-test-file-processing.js"
  "36-component-test-run-history.js"
  "37-component-test-output-resize.js"
  "38-fork-copy.js"
  "39-output-utils-run.js"
  "40-output-renderers.js"
  "41-init-exports.js"
  "42-block-editor-core.js"
  "43-block-editor-actions.js"
  "44-auth-bootstrap.js"
)

INLINE_ONLY_MODULES=(
  "inline-only/inline-overrides.js"
)

usage() {
  cat <<'EOF'
Usage:
  ./build-algo-lib.sh check   只合并生成 .run/algo-lib-check.js
  ./build-algo-lib.sh inline  只合并生成 .run/algo-lib-inline-check.js
  ./build-algo-lib.sh inject  合并 inline 版本并注入到 src/browser/pages/algo-lib.html
  ./build-algo-lib.sh all     合并两个版本并注入到 src/browser/pages/algo-lib.html
  ./build-algo-lib.sh dev     all + 执行 ci/dev/sync-and-restart.sh --full
EOF
}

timestamp() {
  date '+%Y-%m-%d %H:%M:%S %z'
}

file_size() {
  wc -c < "$1" | tr -d '[:space:]'
}

write_bundle() {
  local label="$1"
  local output_file="$2"
  shift 2

  local tmp_file
  tmp_file="$(mktemp)"

  {
    echo "// Auto-generated by build-algo-lib.sh at $(timestamp). DO NOT EDIT DIRECTLY."
    echo

    local module
    for module in "$@"; do
      local module_path="${MODULE_DIR}/${module}"
      if [[ ! -f "${module_path}" ]]; then
        echo "Missing module: ${module_path}" >&2
        rm -f "${tmp_file}"
        exit 1
      fi

      echo "// ===== ${module} ====="
      cat "${module_path}"
      echo
    done
  } > "${tmp_file}"

  mv "${tmp_file}" "${output_file}"
  echo "Built ${label}: ${output_file} ($(file_size "${output_file}") bytes)"
}

build_check() {
  write_bundle "check" "${CHECK_OUT}" "${SHARED_MODULES[@]}"
}

build_inline() {
  write_bundle "inline" "${INLINE_OUT}" "${SHARED_MODULES[@]}" "${INLINE_ONLY_MODULES[@]}"
}

marker_count() {
  local marker="$1"
  local file="$2"
  grep -F "${marker}" "${file}" | wc -l | tr -d '[:space:]'
}

assert_inject_ready() {
  echo "==> 检查 HTML 注入条件"

  [[ -f "${HTML_FILE}" ]] || {
    echo "HTML 文件不存在：${HTML_FILE}" >&2
    exit 1
  }

  [[ -s "${INLINE_OUT}" ]] || {
    echo "inline 构建产物不存在或为空：${INLINE_OUT}" >&2
    exit 1
  }

  local start_count
  local end_count
  start_count="$(marker_count "${START_MARKER}" "${HTML_FILE}")"
  end_count="$(marker_count "${END_MARKER}" "${HTML_FILE}")"

  if [[ "${start_count}" != "1" ]]; then
    echo "START 标记必须出现且只出现一次，当前次数：${start_count}" >&2
    echo "标记：${START_MARKER}" >&2
    exit 1
  fi

  if [[ "${end_count}" != "1" ]]; then
    echo "END 标记必须出现且只出现一次，当前次数：${end_count}" >&2
    echo "标记：${END_MARKER}" >&2
    exit 1
  fi
}

inject_inline() {
  echo "==> 注入 inline JS 到 HTML"
  assert_inject_ready

  cp "${HTML_FILE}" "${HTML_BACKUP}"
  echo "  已备份：${HTML_BACKUP}"

  local tmp_file
  tmp_file="$(mktemp)"

  if ! awk -v start="${START_MARKER}" -v end="${END_MARKER}" -v js_file="${INLINE_OUT}" '
    BEGIN {
      while ((getline js_line < js_file) > 0) {
        js_content = js_content js_line "\n"
      }
      close(js_file)
      in_block = 0
      replaced = 0
    }
    index($0, start) {
      print
      printf "%s", js_content
      in_block = 1
      replaced = 1
      next
    }
    index($0, end) {
      in_block = 0
      print
      next
    }
    !in_block {
      print
    }
    END {
      if (in_block || !replaced) {
        exit 2
      }
    }
  ' "${HTML_FILE}" > "${tmp_file}"; then
    rm -f "${tmp_file}"
    echo "注入失败，HTML 未修改。" >&2
    exit 1
  fi

  mv "${tmp_file}" "${HTML_FILE}"
  echo "  注入完成：${HTML_FILE} ($(file_size "${HTML_FILE}") bytes)"
}

build_inject() {
  build_inline
  inject_inline
}

build_all() {
  build_check
  build_inline
  inject_inline
}

build_dev() {
  build_all
  echo "==> 同步到 WSL 并重启 code-server/full 与 algo-service"
  local sync_script="${REPO_ROOT}/ci/dev/sync-and-restart.sh"
  local wsl_project_dir="${ALGOLIB_WSL_PROJECT_DIR:-/home/guan/code-server-me}"

  # 如果从 /mnt/e/code-server-me 运行本脚本，真正的同步脚本应在 /home/guan/code-server-me 中执行，
  # 这样 sync-and-restart.sh 才会把 /mnt/e/code-server-me 同步到 /home/guan/code-server-me。
  if [[ "${REPO_ROOT}" == /mnt/* && -f "${wsl_project_dir}/ci/dev/sync-and-restart.sh" ]]; then
    sync_script="${wsl_project_dir}/ci/dev/sync-and-restart.sh"
  fi

  bash "${sync_script}" --full
}

main() {
  local target="${1:-all}"

  case "${target}" in
    check)
      build_check
      ;;
    inline)
      build_inline
      ;;
    inject)
      build_inject
      ;;
    all)
      build_all
      ;;
    dev)
      build_dev
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
